import React from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/detailedReport.module.css'
import mypic from '../public/blackboxgraph.png'
import home from '../public/home.png'
import notf from '../public/notf.png'
import search from '../public/search.png'
import prof from '../public/prof.png'
import done from '../public/done.png'
import reportimg from '../public/ReportImg.png'
import reportimg2 from '../public/ReportImg2.png'

function detailedReport() {
  return (
    <div>

    <Head>
        <title>Emergent</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
       
      <div className={styles.Topbar} >

            <div className={styles.Searchbox}>

              <div className={styles.homebox3}>
                <Image
                    src={search}
                />
              </div>
              
              <p  className={styles.Searchboxtext}>Search</p>
            </div>


     <div className={styles.Topbar2}>

             <div className={styles.homebox}> 
             <Image
             src={home}
             />
             </div>
             <div className={styles.homebox2}>
              <Image
              src={notf}
              />
              
               </div>
               <div className={styles.homebox4}>
                <Image
                src={prof}
                />
               </div>
             <p className={styles.hometxt}>Surya Narayanan</p>
             <div className={styles.homebox2}> 
             <Image
             src={done}
             />
             </div>

     </div>
            
    </div>

    <div className={styles.backgroundBox}>
        <h1 className={styles.heading}>Surya’s Health Records</h1>

    <div className={styles.liveDataCard}>
        <div className={styles.flexRow}>
            <div className={styles.dataName}>Hematology Report</div>
            <div className={styles.dataTime}>25-MAY-2022</div>
        </div>

        <div className={styles.recordID}><b>Test ID:</b> SURYANAYA0004</div>

        <div className={styles.detailsData}><b> Hosp/Lab:</b> Graham Nursing Home</div>
        <div className={styles.detailsData}><b>Ref. By:</b> Dr. Sankar M.S.,M.Ch(Uro)</div>
        <div className={styles.detailsData}><b>Test Purpose: </b>Regular checkup on the Blood Level to have
                                  proper medication.</div>

        <div className={styles.getDetails}><span className={styles.updateBlue}>Update</span>     <span className={styles.reportRed}>Report</span></div>
    </div>

    <div className={styles.medicalReports}>
        <div className={styles.reportImage}><Image
            src={reportimg}
            alt="Picture of the author"
        /></div>

        <div className={styles.reportImage}><Image
          src={reportimg2}
          alt="Picture of the author"
        /></div>
    </div>

    </div>

    </div>
  )
}

export default detailedReport