import React from 'react'
import Head from 'next/head'
import Image from 'next/image'
// import styles from '../styles/Home.module.css'
import styles from '../styles/liveMedicalRecord.module.css'
import mypic from '../public/blackboxgraph.png'
import home from '../public/home.png'
import notf from '../public/notf.png'
import search from '../public/search.png'
import prof from '../public/prof.png'
import done from '../public/done.png'

function liveMedicalRecord() {
  return (
    <div className={styles.container}>

    <Head>
        <title>Emergent</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
       
      <div className={styles.Topbar} >

            <div className={styles.Searchbox}>

              <div className={styles.homebox3}>
                <Image
                    src={search}
                />
              </div>
              
              <p  className={styles.Searchboxtext}>Search</p>
            </div>


     <div className={styles.Topbar2}>

             <div className={styles.homebox}> 
             <Image
             src={home}
             />
             </div>
             <div className={styles.homebox2}>
              <Image
              src={notf}
              />
              
               </div>
               <div className={styles.homebox4}>
                <Image
                src={prof}
                />
               </div>
             <p className={styles.hometxt}>Surya Narayanan</p>
             <div className={styles.homebox2}> 
             <Image
             src={done}
             />
             </div>

     </div>
            
    </div>

    <div className={styles.backgroundBox}>
        <h1 className={styles.heading}>Live Health Data</h1>

        <div className={styles.dataGrid}>
            <div className={styles.liveDataCard}>
                <div className={styles.flexRow}>
                    <div className={styles.dataName}>Pulse Rate</div>
                    <div className={styles.dataTime}>07-DEC-2021</div>
                </div>

                <div className={styles.recordID}>Record ID: 2200228447</div>

                <div className={styles.liveData}>76/min</div>
                <div className={styles.liveDataActual}>74/min</div>
            </div>

            <div className={styles.liveDataCard}>
                <div className={styles.flexRow}>
                    <div className={styles.dataName}>ECB (bpm)</div>
                    <div className={styles.dataTime}>07-DEC-2021</div>
                </div>

                <div className={styles.recordID}>Record ID: 2200228447</div>

                <div className={styles.liveData}>80</div>
                <div className={styles.liveDataActual}>74/min</div>
            </div>

            <div className={styles.liveDataCard}>
                <div className={styles.flexRow}>
                    <div className={styles.dataName}>SpO2</div>
                    <div className={styles.dataTime}>07-DEC-2021</div>
                </div>

                <div className={styles.recordID}>Record ID: 2200228447</div>

                <div className={styles.liveData}>99</div>
                <div className={styles.liveDataActual}></div>
            </div>

            <div className={styles.liveDataCard}>
                <div className={styles.flexRow}>
                    <div className={styles.dataName}>IBP</div>
                    <div className={styles.dataTime}>07-DEC-2021</div>
                </div>

                <div className={styles.recordID}>Record ID: 2200228447</div>

                <div className={styles.liveData}>120/80</div>
                <div className={styles.liveDataActual}>93mmHg</div>
            </div>

            <div className={styles.liveDataCard}>
                <div className={styles.flexRow}>
                    <div className={styles.dataName}>RESP</div>
                    <div className={styles.dataTime}>07-DEC-2021</div>
                </div>

                <div className={styles.recordID}>Record ID: 2200228447</div>

                <div className={styles.liveData}>14</div>
                <div className={styles.liveDataActual}></div>
            </div>
        </div>
    </div>

    </div>
  )
}

export default liveMedicalRecord