import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import mypic from '../public/blackboxgraph.png'
import home from '../public/home.png'
import notf from '../public/notf.png'
import search from '../public/search.png'
import prof from '../public/prof.png'
import done from '../public/done.png'


export default function Home() {
    return (
      <div className={styles.container}>
        <Head>
          <title>Emergent</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
  
    
<main className={styles.main}>
       
<div className={styles.Topbar} >
 
    <div className={styles.Searchbox}>
 
        <div className={styles.homebox3}>
                 <Image
               src={search}
               />
        </div>
               
               <p  className={styles.Searchboxtext}>Search</p>
    </div>
 
 
      <div className={styles.Topbar2}>
 
              <div className={styles.homebox}> 
              <Image
              src={home}
              />
              </div>

              <div className={styles.homebox2}>
               <Image
               src={notf}
               />
              </div>
                 <div className={styles.homebox4}>
                 <Image
                 src={prof}
                 />
                 </div>
              <p className={styles.hometxt}>Surya Narayanan</p>
               <div className={styles.homebox2}> 
                    <Image
                     src={done}
                  />
               </div>
 
      </div>
             
        </div>

        </main>

      <footer className={styles.footer}>
      
      </footer>
    </div>
  )
}
